### ISSUE TITLE
Sample not working with deno 2.1.2

### ISSUE THREAD

**Issue by smartmeta** [JOTSR/Deplot#3]
I'm running

```
deno run --allow-read --allow-write --allow-env --allow-ffi --unstable https://deno.land/x/deplot/examples/chartjs.ts
```

on

``` deno --version
deno 2.1.1 (stable, release, aarch64-apple-darwin)
v8 13.0.245.12-rusty
typescript 5.6.2
```

and get

```
The `--unstable` flag has been removed in Deno 2.0. Use granular `--unstable-*` flags instead.
Learn more at: https://docs.deno.com/runtime/manual/tools/unstable_flags
✅ Granted all import access.
error: Import assertions are deprecated. Use `with` keyword, instead of 'assert' keyword.

export {
  //@ts-ignore ejm serve { b64: string }
  default as webui2Darwin,
} from "https://ejm.sh/raw.githubusercontent.com/webui-dev/deno-webui/6fa36e7c15b6ea643e52d9edfcd2fac102d313ce/src/webui-2-x64.dyn" assert {
  type: "json",
};

  at https://raw.githubusercontent.com/webui-dev/deno-webui/3ba9bbc9ffd9de870a12b946a7515fa7ede7d38e/deps.ts:2:1
```

same for plotty

```
 deno run --allow-read --allow-write --allow-env --allow-ffi --unstable https://deno.land/x/deplot/examples/plotly.ts 
```

```
⚠️  The `--unstable` flag has been removed in Deno 2.0. Use granular `--unstable-*` flags instead.
Learn more at: https://docs.deno.com/runtime/manual/tools/unstable_flags
✅ Granted all import access.
error: Import assertions are deprecated. Use `with` keyword, instead of 'assert' keyword.

export {
  //@ts-ignore ejm serve { b64: string }
  default as webui2Darwin,
} from "https://ejm.sh/raw.githubusercontent.com/webui-dev/deno-webui/6fa36e7c15b6ea643e52d9edfcd2fac102d313ce/src/webui-2-x64.dyn" assert {
  type: "json",
};

  at https://raw.githubusercontent.com/webui-dev/deno-webui/3ba9bbc9ffd9de870a12b946a7515fa7ede7d38e/deps.ts:2:1

```
---
Just noticed that 2.1.2 is available. 
Now I'm on

```
deno 2.1.2 (stable, release, aarch64-apple-darwin)
v8 13.0.245.12-rusty
typescript 5.6.2
```

but the errors are still the same. 
By the way I get the same errors when running the code in a local file.

**Comment by JOTSR** [comment]
The rendering currently depends on deno_webui (and before unmaintained? deno_webview). I rewriting a new rendering pipeline and decouple rendering and ploting. It take me some time but the new version (supporting deno@2 and jsr) is on road.
